const questions = [
    { id: 1, question: "What did you work on today?" },
    { id: 2, question: "What do you aim to accomplish today?" },
    { id: 3, question: "What are your must-wins for today?" },
    { id: 4, question: "What work did you accomplish today that you are most proud of?" },
    { id: 5, question: "What are your priorities for today?" },
    { id: 6, question: "What are the top three things you need to do today?" },
    { id: 7, question: "What are your must-wins for the week?" },
    { id: 8, question: "What is one way you could become a better teammate?" },
    { id: 9, question: "What gave you energy today?" },
    { id: 10, question: "What drained you today?" },
    { id: 11, question: "What would you like to be working on next week? Next year? In five years?" },
    { id: 12, question: "When was the last time you said, 'thank you' to a coworker?" },
    { id: 13, question: "When was the last time you asked for feedback on your work?" },
    { id: 14, question: "What does success at work look like for you?" },
    { id: 15, question: "In X years, what would you like to be doing for work?" },
    { id: 16, question: "How can you make your life better today?" },
    { id: 17, question: "What brings you energy?" },
    { id: 18, question: "What drains you right now?" },
    { id: 19, question: "In a couple of sentences, describe what's going on right now." },
    { id: 20, question: "How was your week?" },
    { id: 21, question: "What are you most proud of right now?" },
    { id: 22, question: "What would you like to improve about your life in the next 30 days?" },
    { id: 23, question: "What does success look like to you?" },
    { id: 24, question: "Who is the most important person in your life right now. Why?" },
    { id: 25, question: "What is bringing you joy right now?" },
    { id: 26, question: "What is making you sad right now?" },
    { id: 27, question: "What are you thankful for right now?" },
    { id: 28, question: "Who should you connect with right now? When was the last time you talked with them?" },
    { id: 29, question: "How is social media impacting your life right now?" },
    { id: 30, question: "What was the most surprising event you experienced this week?" },
    { id: 31, question: "What do you want your legacy to be?" },
    { id: 32, question: "When was the last time you exercised. Why?" },
    { id: 33, question: "What places would you like to visit this year?" },
    { id: 34, question: "What was the most exciting thing that happened this week?" },
    { id: 35, question: "List the three people that give you energy" },
    { id: 36, question: "What is one problem you encountered this week? How did you go about solving it?" },
    { id: 37, question: "What is worrying you right now?" },
    { id: 38, question: "What was the most disappointing thing you encountered recently. How did you overcome it?" },
    { id: 39, question: "Rate how you are handling stress right now. Why?" },
    { id: 40, question: "What is making you nervous right now?" },
    { id: 41, question: "What is one good thing that happened to you today?" },
    { id: 42, question: "What is your biggest overall accomplishment?" },
    { id: 43, question: "What is the best thing that happened this week?" },
    { id: 44, question: "What is something you had to overcome?" },
    { id: 45, question: "What is something that makes you happy?" },
    { id: 46, question: "What was your favorite part of your day?" },
    { id: 47, question: "When you feel down, what makes you smile?" },
    { id: 48, question: "What is a random act of kindness you've done or witnessed recently?" },
    { id: 49, question: "What is your favorite hobby?" },
    { id: 50, question: "What are three things you take for granted?" },
    { id: 51, question: "What are you looking forward to today?" },
    { id: 52, question: "What is something you wish to have done differently?" },
    { id: 53, question: "What did you think about the most today?" },
    { id: 54, question: "What are you looking forward to tomorrow?" },
    { id: 55, question: "What's the first thing that came up in your mind today?" },
    { id: 56, question: "What is something you learned today?" },
    { id: 57, question: "What hobby do you want to learn more about?" },
    { id: 58, question: "What is your biggest roadblock to overcome today?" },
    { id: 59, question: "Are there any distractions impacting your day?" },
    { id: 60, question: "What was your favorite thing to do today?" }
  ];  

export default questions;